name: 'build and deploy python az function'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'       
  PYTHON_VERSION: '3.9'

jobs:
  Build:
    runs-on: ubuntu-latest        
    steps:
    - uses: actions/checkout@v2         
    
    - name: Upload artifacts for deployment
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment: development
    steps:
    
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: app
        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
                     
    - name: 'Run Azure webapp deploy action using spn'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ vars.AZURE_FUNCTION_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 
        scm-do-build-during-deployment: true
        enable-oryx-build: true         
      
    - name: logout
      run: |
        az logout        
