name: 'build and deploy python az function'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'       
  PYTHON_VERSION: '3.9'

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v2         
    
#     - name: 'Set up Python ${{ env.PYTHON_VERSION }}'
#       uses: actions/setup-python@v2
#       with:
#         python-version: '${{ env.PYTHON_VERSION }}'
        
#     - name: Install dependencies
#       run: |
#          pushd './${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
#          popd
           
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
                
    # Deploy to Azure function   
    - name: 'Run Azure webapp deploy action using spn'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ vars.AZURE_FUNCTION_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}      
        scm-do-build-during-deployment: true
        enable-oryx-build: true         
      
    - name: logout
      run: |
        az logout        
